-version 5.00.1  i've started building it 6h30m ago and it's stil building on by  k6-2/300, so i'm not sure if this is correct (but I hope so)
Changed files:
    ghc-DESTDIR.patch -> 1.2
    ghc.spec -> 1.2

diff --git a/ghc-DESTDIR.patch b/ghc-DESTDIR.patch
--- a/ghc-DESTDIR.patch
+++ b/ghc-DESTDIR.patch
@@ -1,20 +1,46 @@
---- fptools/mk/target.mk~	Mon Aug  7 18:00:59 2000
-+++ fptools/mk/target.mk	Sat Nov 18 23:48:17 2000
-@@ -607,10 +607,10 @@
+--- ./mk/target.mk.org	Sun Jun 24 17:25:42 2001
++++ ./mk/target.mk	Sun Jun 24 17:31:40 2001
+@@ -686,13 +686,13 @@
  # on perl.
  #
- $(SCRIPT_LINK) : $(SCRIPT_PROG)
--	@if ( $(PERL) -e '$$fn="$(SCRIPT_LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
-+	@if ( $(PERL) -e '$$fn="$(DESTDIR)$(SCRIPT_LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
- 	   echo "Creating a symbolic link from $(SCRIPT_PROG) to $(SCRIPT_LINK)"; \
--	   $(RM) $(SCRIPT_LINK); \
--	   $(LN_S) $(SCRIPT_PROG) $(SCRIPT_LINK); \
-+	   $(RM) $(DESTDIR)$(SCRIPT_LINK); \
-+	   $(LN_S) $(SCRIPT_PROG) $(DESTDIR)$(SCRIPT_LINK); \
+ $(LINK) : $(LINK_TARGET)
+-	@if ( $(PERL) -e '$$fn="$(LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
+-	   echo "Creating a symbolic link from $(LINK_TARGET) to $(LINK)"; \
+-	   $(RM) $(LINK); \
+-	   $(LN_S) $(LINK_TARGET) $(LINK); \
++	@if ( $(PERL) -e '$$fn="$(DESTDIR)$(LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
++	   echo "Creating a symbolic link from $(LINK_TARGET) to $(DESTDIR)$(LINK)"; \
++	   $(RM) $(DESTDIR)$(LINK); \
++	   $(LN_S) $(LINK_TARGET) $(DESTDIR)$(LINK); \
  	 else \
- 	   echo "Creating a symbolic link from $(SCRIPT_PROG) to $(SCRIPT_LINK) failed: \`$(SCRIPT_LINK)' already exists"; \
- 	   echo "Perhaps remove \`$(SCRIPT_LINK)' manually?"; \
-@@ -656,10 +656,10 @@
+-	   echo "Creating a symbolic link from $(LINK_TARGET) to $(LINK) failed: \`$(LINK)' already exists"; \
+-	   echo "Perhaps remove \`$(LINK)' manually?"; \
++	   echo "Creating a symbolic link from $(LINK_TARGET) to $(DESTDIR)$(LINK) failed: \`$(DESTDIR)$(LINK)' already exists"; \
++	   echo "Perhaps remove \`$(DESTDIR)$(LINK)' manually?"; \
+ 	   exit 1; \
+ 	 fi;
+ 
+@@ -701,13 +701,13 @@
+ # install links to script drivers.
+ #
+ install ::
+-	@if ( $(PERL) -e '$$fn="$(bindir)/$(LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
+-	   echo "Creating a symbol link from $(LINK_TARGET) to $(LINK) in $(bindir)"; \
+-	   $(RM) $(bindir)/$(LINK); \
+-	   $(LN_S) $(LINK_TARGET) $(bindir)/$(LINK); \
++	@if ( $(PERL) -e '$$fn="$(DESTDIR)$(bindir)/$(LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
++	   echo "Creating a symbol link from $(LINK_TARGET) to $(LINK) in $(DESTDIR)$(bindir)"; \
++	   $(RM) $(DESTDIR)$(bindir)/$(LINK); \
++	   $(LN_S) $(LINK_TARGET) $(DESTDIR)$(bindir)/$(LINK); \
+ 	 else \
+-	   echo "Creating a symbol link from $(LINK_TARGET) to $(LINK) in $(bindir) failed: \`$(bindir)/$(LINK)' already exists"; \
+-	   echo "Perhaps remove \`$(bindir)/$(LINK)' manually?"; \
++	   echo "Creating a symbol link from $(LINK_TARGET) to $(LINK) in $(DESTDIR)$(bindir) failed: \`$(DESTDIR)$(bindir)/$(LINK)' already exists"; \
++	   echo "Perhaps remove \`$(DESTDIR)$(bindir)/$(LINK)' manually?"; \
+ 	   exit 1; \
+ 	 fi;
+ 
+@@ -750,10 +750,10 @@
  # from the installation itself.
  #
  install-dirs ::
@@ -29,21 +55,16 @@
  
  # Better do this first...
  # but we won't for the moment, do it on-demand from
-@@ -686,10 +686,10 @@
- INSTALL_PROGS := $(foreach p, $(INSTALL_PROGS), $(addsuffix $(subst _,,$(subst __,$(exeext),_$(suffix $(p))_)), $(basename $(p))))
- 
- install:: $(INSTALL_PROGS)
--	@$(INSTALL_DIR) $(bindir)
-+	@$(INSTALL_DIR) $(DESTDIR)$(bindir)
+@@ -793,7 +793,7 @@
+ 	@$(INSTALL_DIR) $(bindir)
  	@for i in $(INSTALL_PROGS); do \
--		    echo $(INSTALL_PROGRAM) $(INSTALL_BIN_OPTS) $$i $(bindir); \
+ 		    echo $(INSTALL_PROGRAM) $(INSTALL_BIN_OPTS) $$i $(bindir); \
 -		    $(INSTALL_PROGRAM) $(INSTALL_BIN_OPTS) $$i $(bindir) ;  \
-+		    echo $(INSTALL_PROGRAM) $(INSTALL_BIN_OPTS) $$i $(DESTDIR)$(bindir); \
 +		    $(INSTALL_PROGRAM) $(INSTALL_BIN_OPTS) $$i $(DESTDIR)$(bindir) ;  \
  	done
  endif
  
-@@ -699,40 +699,40 @@
+@@ -803,40 +803,40 @@
  #
  ifneq "$(INSTALL_SCRIPTS)" ""
  install:: $(INSTALL_SCRIPTS)
@@ -95,7 +116,7 @@
  		esac; \
  	done
  endif
-@@ -745,25 +745,25 @@
+@@ -849,25 +849,25 @@
  INSTALL_LIBEXECS := $(foreach p, $(INSTALL_LIBEXECS), $(addsuffix $(subst _,,$(subst __,$(exeext),_$(suffix $(p))_)), $(basename $(p))))
  
  install:: $(INSTALL_LIBEXECS)
@@ -127,17 +148,38 @@
  	done
  endif
  
-@@ -809,10 +809,10 @@
- #
- ifneq "$(SCRIPT_LINK)" ""
- install ::
--	@if ( $(PERL) -e '$$fn="$(bindir)/$(SCRIPT_LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
-+	@if ( $(PERL) -e '$$fn="$(DESTDIR)$(bindir)/$(SCRIPT_LINK)"; exit ((! -f $$fn || -l $$fn) ? 0 : 1);' ); then \
- 	   echo "Creating a symbol link from $(SCRIPT_PROG) to $(SCRIPT_LINK) in $(bindir)"; \
--	   $(RM) $(bindir)/$(SCRIPT_LINK); \
--	   $(LN_S) $(SCRIPT_PROG) $(bindir)/$(SCRIPT_LINK); \
-+	   $(RM) $(DESTDIR)$(bindir)/$(SCRIPT_LINK); \
-+	   $(LN_S) $(SCRIPT_PROG) $(DESTDIR)$(bindir)/$(SCRIPT_LINK); \
- 	 else \
- 	   echo "Creating a symbol link from $(SCRIPT_PROG) to $(SCRIPT_LINK) in $(bindir) failed: \`$(bindir)/$(SCRIPT_LINK)' already exists"; \
- 	   echo "Perhaps remove \`$(bindir)/$(SCRIPT_LINK)' manually?"; \
+@@ -877,26 +877,26 @@
+ uninstall:: 
+ 	@for i in $(INSTALL_PROGS) "" ; do			\
+ 	  if test "$$i"; then 					\
+-		echo rm -f $(bindir)/`basename $$i`;		\
+-		rm -f $(bindir)/`basename $$i`;			\
++		echo rm -f $(DESTDIR)$(bindir)/`basename $$i`;		\
++		rm -f $(DESTDIR)$(bindir)/`basename $$i`;			\
+ 	  fi; 							\
+ 	done
+ 	@for i in $(INSTALL_LIBS) ""; do			\
+ 	  if test "$$i"; then 					\
+-		echo rm -f $(libdir)/`basename $$i`;		\
+-		rm -f $(libdir)/`basename $$i`;			\
++		echo rm -f $(DESTDIR)$(libdir)/`basename $$i`;		\
++		rm -f $(DESTDIR)$(libdir)/`basename $$i`;			\
+ 	  fi;							\
+ 	done
+ 	@for i in $(INSTALL_LIBEXECS) ""; do			\
+ 	  if test "$$i"; then 					\
+-		echo rm -f $(libexecdir)/`basename $$i`;	\
+-		rm -f $(libexecdir)/`basename $$i`;		\
++		echo rm -f $(DESTDIR)$(libexecdir)/`basename $$i`;	\
++		rm -f $(DESTDIR)$(libexecdir)/`basename $$i`;		\
+ 	  fi;							\
+ 	done
+ 	@for i in $(INSTALL_DATAS) ""; do			\
+ 	  if test "$$i"; then 					\
+-		echo rm -f $(datadir)/`basename $$i`;		\
+-		rm -f $(datadir)/`basename $$i`;		\
++		echo rm -f $(DESTDIR)$(datadir)/`basename $$i`;		\
++		rm -f $(DESTDIR)$(datadir)/`basename $$i`;		\
+ 	  fi;							\
+ 	done
+ 
